<?php
return array (
  51 => 
  array (
    'id' => 51,
    'name' => '行业企业',
    'dirname' => 'company',
    'urlrules' => 'a:6:{s:4:"list";a:3:{s:7:"tplfile";s:4:"list";s:5:"rules";s:32:"newslist/{数字1}{id}{数字1}/";s:6:"system";s:1:"1";}s:4:"show";a:3:{s:7:"tplfile";s:4:"show";s:5:"rules";s:116:"html/{日期}/{数字1}{id}{数字2}.html,news/{日期}/{数字1}{id}{数字2}.html,show/{数字1}{id}{数字2}.html";s:6:"system";s:1:"1";}s:7:"contact";a:3:{s:7:"tplfile";s:7:"contact";s:5:"rules";s:70:"contact/,contact.html,lianxi.html,contact/{数字3}/,lianxi/{数字3}/";s:6:"system";s:1:"0";}s:5:"about";a:3:{s:7:"tplfile";s:5:"about";s:5:"rules";s:79:"about/,aboutus/,about.html,about/{数字3}/,about_{数字3}/,aboutus/{数字3}/";s:6:"system";s:1:"0";}s:12:"product_list";a:3:{s:7:"tplfile";s:12:"product_list";s:5:"rules";s:141:"product/list_{数字1}{数字2}.html,product/index_{数字1}{数字2}.html,product/list_{数字1}{数字2}/,product/index_{数字1}{数字2}/";s:6:"system";s:0:"";}s:12:"product_show";a:3:{s:7:"tplfile";s:12:"product_show";s:5:"rules";s:100:"product/{数字2}{数字2}.html,product/show_{数字2}{数字2}.html,product/show{数字2}{数字2}/";s:6:"system";s:0:"";}}',
    'tplrules' => '10',
    'temp1' => '',
    'temp2' => '',
    'temp3' => '1',
    'temp4' => 99,
    'temp5' => '',
    'temp6' => '',
  ),
  52 => 
  array (
    'id' => 52,
    'name' => '文章新闻',
    'dirname' => 'news',
    'urlrules' => 'a:2:{s:4:"list";a:3:{s:7:"tplfile";s:4:"list";s:5:"rules";s:61:"list/{数字1}{id}{数字2}/,newslist/{数字1}{id}{数字2}/";s:6:"system";s:1:"1";}s:4:"show";a:3:{s:7:"tplfile";s:4:"show";s:5:"rules";s:98:"html/{日期}/{数字1}{id}{数字3}.html,news/{数字3}{id}{数字2}.html,show/{id}{数字5}.html";s:6:"system";s:1:"1";}}',
    'tplrules' => '10',
    'temp1' => '',
    'temp2' => '',
    'temp3' => 1,
    'temp4' => 98,
    'temp5' => '',
    'temp6' => '',
  ),
  53 => 
  array (
    'id' => 53,
    'name' => '小说网站',
    'dirname' => 'xiaoshuo',
    'urlrules' => 'a:3:{s:4:"list";a:3:{s:7:"tplfile";s:4:"list";s:5:"rules";s:202:"category/{数字1}{id}{数字2}.html,class/{数字1}{id}{数字2}.html,list/{数字1}{id}{数字2}.html,readlist/{数字1}{id}{数字2}.html,list/{字母1}{id}{字母1}/,category/{字母1}{id}{字母1}/";s:6:"system";s:1:"1";}s:4:"show";a:3:{s:7:"tplfile";s:4:"show";s:5:"rules";s:102:"download/{数字2}{id}{数字2}.html,html/{数字2}{id}{数字2}.html,read/{数字2}{id}{数字2}.html";s:6:"system";s:1:"1";}s:7:"chapter";a:3:{s:7:"tplfile";s:7:"chapter";s:5:"rules";s:106:"chapter/{数字2}{id}{数字2}/{数字2}/,chapter/{数字2}{id}{数字2}/,zhangjie/{数字2}{id}{数字2}/";s:6:"system";s:0:"";}}',
    'tplrules' => '10',
    'temp1' => '',
    'temp2' => '',
    'temp3' => 1,
    'temp4' => 97,
    'temp5' => '',
    'temp6' => '',
  ),
  54 => 
  array (
    'id' => 54,
    'name' => '电影视频',
    'dirname' => 'video',
    'urlrules' => 'a:2:{s:4:"list";a:3:{s:7:"tplfile";s:4:"list";s:5:"rules";s:123:"videolist/{数字2}{id}{数字2}/,list/{数字2}{id}{数字2}/,tvlist/{数字2}{id}{数字2}/,movie/{数字2}{id}{数字2}/";s:6:"system";s:1:"1";}s:4:"show";a:3:{s:7:"tplfile";s:4:"show";s:5:"rules";s:131:"video/{数字2}{id}{数字2}.html,html/{数字2}{id}{数字2}.html,tv/{数字2}{id}{数字2}.html,movie/{数字2}{id}{数字2}.html";s:6:"system";s:1:"1";}}',
    'tplrules' => '10',
    'temp1' => '',
    'temp2' => '',
    'temp3' => 1,
    'temp4' => 96,
    'temp5' => '',
    'temp6' => '',
  ),
  55 => 
  array (
    'id' => 55,
    'name' => '论坛社区',
    'dirname' => 'bbs',
    'urlrules' => 'a:2:{s:4:"list";a:3:{s:7:"tplfile";s:4:"list";s:5:"rules";s:195:"forum/{数字2}{id}{数字2}/,forum/{数字2}{id}/,forum/{日期}/{数字2}{id}/,forum-{数字2}{id}{数字2}-1.html,forum-{数字1}{id}{数字1}-{数字1}.html,forum-{数字1}{id}-{数字1}.html";s:6:"system";s:1:"1";}s:4:"show";a:3:{s:7:"tplfile";s:4:"show";s:5:"rules";s:232:"thread-{数字2}{id}{数字2}-1-1.html,thread-{数字1}{id}{数字1}.html,thread-{数字1}{id}{数字2}-{数字1}-1.html,thread/{数字2}{id}{数字2}.html,html/{数字2}{id}{数字2}.html,thread/{日期}/{数字2}{id}{数字1}.html";s:6:"system";s:1:"1";}}',
    'tplrules' => '10',
    'temp1' => '',
    'temp2' => '',
    'temp3' => 1,
    'temp4' => 95,
    'temp5' => '',
    'temp6' => '',
  ),
  64 => 
  array (
    'id' => 64,
    'name' => '聊城信息港',
    'dirname' => 'liaocheng',
    'urlrules' => 'a:28:{s:4:"list";a:3:{s:7:"tplfile";s:4:"list";s:5:"rules";s:209:"fangchan_{数字5}/,zhaopin_{数字5}/,ershou_{数字5}/,jiaoyou_{数字5}/,shenghuo_{数字5}/,zhidao_{数字5}/,blog_{数字5}/,qiye_{数字5}/,news_{数字5}/,keji_{数字5}/,bbs_{数字5}/,lvyou_{数字5}/";s:6:"system";s:1:"1";}s:4:"show";a:3:{s:7:"tplfile";s:4:"show";s:5:"rules";s:353:"fangchan/{日期}{字母5}.html,zhaopin/{日期}{字母5}.html,ershou/{日期}{字母5}.html,jiaoyou/{日期}{字母5}.html,shenghuo/{日期}{字母5}.html,zhidao/{日期}{字母5}.html,blog/{日期}{字母5}.html,qiye/{日期}{字母5}.html,news/{日期}{字母5}.html,keji/{日期}{字母5}.html,bbs/{日期}{字母5}.html,lvyou/{日期}{字母5}.html";s:6:"system";s:1:"1";}s:8:"bbs_list";a:3:{s:7:"tplfile";s:8:"bbs_list";s:5:"rules";s:49:"bbs/,bbs_{数字5}/,bbs_{数字5}/,bbs_{数字5}/";s:6:"system";s:0:"";}s:3:"bbs";a:3:{s:7:"tplfile";s:3:"bbs";s:5:"rules";s:26:"bbs/{日期}{字母5}.html";s:6:"system";s:0:"";}s:9:"keji_list";a:3:{s:7:"tplfile";s:9:"keji_list";s:5:"rules";s:53:"keji/,keji_{数字5}/,keji_{数字5}/,keji_{数字5}/";s:6:"system";s:0:"";}s:4:"news";a:3:{s:7:"tplfile";s:4:"news";s:5:"rules";s:27:"news/{日期}{字母5}.html";s:6:"system";s:0:"";}s:9:"news_list";a:3:{s:7:"tplfile";s:9:"news_list";s:5:"rules";s:53:"news/,news_{数字5}/,news_{数字5}/,news_{数字5}/";s:6:"system";s:0:"";}s:4:"qiye";a:3:{s:7:"tplfile";s:4:"qiye";s:5:"rules";s:27:"qiye/{日期}{字母5}.html";s:6:"system";s:0:"";}s:9:"qiye_list";a:3:{s:7:"tplfile";s:9:"qiye_list";s:5:"rules";s:53:"qiye/,qiye_{数字5}/,qiye_{数字5}/,qiye_{数字5}/";s:6:"system";s:0:"";}s:4:"blog";a:3:{s:7:"tplfile";s:4:"blog";s:5:"rules";s:27:"blog/{日期}{字母5}.html";s:6:"system";s:0:"";}s:9:"blog_list";a:3:{s:7:"tplfile";s:9:"blog_list";s:5:"rules";s:53:"blog/,blog_{数字5}/,blog_{数字5}/,blog_{数字5}/";s:6:"system";s:0:"";}s:6:"zhidao";a:3:{s:7:"tplfile";s:6:"zhidao";s:5:"rules";s:29:"zhidao/{日期}{字母5}.html";s:6:"system";s:0:"";}s:11:"zhidao_list";a:3:{s:7:"tplfile";s:11:"zhidao_list";s:5:"rules";s:61:"zhidao/,zhidao_{数字5}/,zhidao_{数字5}/,zhidao_{数字5}/";s:6:"system";s:0:"";}s:7:"shenhuo";a:3:{s:7:"tplfile";s:7:"shenhuo";s:5:"rules";s:30:"shenhuo/{日期}{字母5}.html";s:6:"system";s:0:"";}s:12:"shenhuo_list";a:3:{s:7:"tplfile";s:12:"shenhuo_list";s:5:"rules";s:65:"shenhuo/,shenhuo_{数字5}/,shenhuo_{数字5}/,shenhuo_{数字5}/";s:6:"system";s:0:"";}s:7:"jiaoyou";a:3:{s:7:"tplfile";s:7:"jiaoyou";s:5:"rules";s:65:"jiaoyou/,jiaoyou_{数字5}/,jiaoyou_{数字5}/,jiaoyou_{数字5}/";s:6:"system";s:0:"";}s:6:"ershou";a:3:{s:7:"tplfile";s:6:"ershou";s:5:"rules";s:29:"ershou/{日期}{字母5}.html";s:6:"system";s:0:"";}s:11:"ershou_list";a:3:{s:7:"tplfile";s:11:"ershou_list";s:5:"rules";s:61:"ershou/,ershou_{数字5}/,ershou_{数字5}/,ershou_{数字5}/";s:6:"system";s:0:"";}s:7:"zhaopin";a:3:{s:7:"tplfile";s:7:"zhaopin";s:5:"rules";s:30:"zhaopin/{日期}{字母5}.html";s:6:"system";s:0:"";}s:12:"zhaopin_list";a:3:{s:7:"tplfile";s:12:"zhaopin_list";s:5:"rules";s:65:"zhaopin/,zhaopin_{数字5}/,zhaopin_{数字5}/,zhaopin_{数字5}/";s:6:"system";s:0:"";}s:8:"fangchan";a:3:{s:7:"tplfile";s:8:"fangchan";s:5:"rules";s:31:"fangchan/{日期}{字母5}.html";s:6:"system";s:0:"";}s:13:"fangchan_list";a:3:{s:7:"tplfile";s:13:"fangchan_list";s:5:"rules";s:69:"fangchan/,fangchan_{数字5}/,fangchan_{数字5}/,fangchan_{数字5}/";s:6:"system";s:0:"";}s:5:"lvyou";a:3:{s:7:"tplfile";s:5:"lvyou";s:5:"rules";s:28:"lvyou/{日期}{字母5}.html";s:6:"system";s:0:"";}s:10:"lvyou_list";a:3:{s:7:"tplfile";s:10:"lvyou_list";s:5:"rules";s:57:"lvyou/,lvyou_{数字5}/,lvyou_{数字5}/,lvyou_{数字5}/";s:6:"system";s:0:"";}s:4:"keji";a:3:{s:7:"tplfile";s:4:"keji";s:5:"rules";s:27:"keji/{日期}{字母5}.html";s:6:"system";s:0:"";}s:12:"jiaoyou_list";a:3:{s:7:"tplfile";s:12:"jiaoyou_list";s:5:"rules";s:65:"jiaoyou/,jiaoyou_{数字5}/,jiaoyou_{数字5}/,jiaoyou_{数字5}/";s:6:"system";s:0:"";}s:13:"bbs_news_list";a:3:{s:7:"tplfile";s:13:"bbs_news_list";s:5:"rules";s:14:"bbs_news_list/";s:6:"system";s:0:"";}s:5:"about";a:3:{s:7:"tplfile";s:5:"about";s:5:"rules";s:10:"about.html";s:6:"system";N;}}',
    'tplrules' => '',
    'temp1' => '',
    'temp2' => '',
    'temp3' => '',
    'temp4' => '',
    'temp5' => '',
    'temp6' => '',
  ),
);
?>